"""Add relationship to Artist

Revision ID: 42f65a5a7074
Revises: cb2b002c7a1b
Create Date: 2024-05-15 20:19:51.605168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f65a5a7074'
down_revision: Union[str, None] = 'cb2b002c7a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
